package tests;

import io.restassured.response.Response;
import org.testng.annotations.Test;
import org.testng.annotations.DataProvider;
import utils.XLUtility;

public class GetAllUsersTest extends BaseTest {

    @Test(dataProvider = "getTestData")
    public void testGetAllUsers(String testType,
                                String testName,
                                String baseUrl,
                                String endpoint,
                                String username,
                                String password,
                                String expectedResult,
                                int rowIndex) {

        System.out.println("Running GetAllUsers test -> " + testName);

        // Get JWT token dynamically
        String token = getAuthToken(baseUrl, username, password);

        // Call API with token
        Response response = io.restassured.RestAssured.given()
                .baseUri(baseUrl)
                .header("Authorization", "Bearer " + token)
                .when()
                .get(endpoint)
                .then()
                .extract()
                .response();

        System.out.println("Response: " + response.asString());

        try {
            if ("PASS".equalsIgnoreCase(expectedResult)) {
                response.then().statusCode(200);
            } else {
                response.then().statusCode(403);
            }

            // Write PASS in Excel
            try {
                XLUtility.setCellData("Tests", rowIndex, 7, "PASS");
            } catch (Exception io) {
                io.printStackTrace(); // log Excel write issue
            }

        } catch (AssertionError e) {
            // Write FAIL in Excel
            try {
                XLUtility.setCellData("Tests", rowIndex, 7, "FAIL");
            } catch (Exception io) {
                io.printStackTrace(); // log Excel write issue
            }
            throw e; // rethrow so TestNG reports failure
        }
    }

    @DataProvider
    public Object[][] getTestData() throws Exception {
        return XLUtility.getTestData("Tests");
    }
}
