package tests;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.Test;

public class GetAllUsersTest extends BaseTest {

    @Test(dataProvider = "getAllUsersData")
    public void testGetAllUsers(String testType, String testName, String baseUrl, String endpoint,
                                String username, String password, String result, int rowIndex) throws Exception {
        System.out.println("Running GetAllUsers test -> " + testName);

        Response response = RestAssured.given()
                .baseUri(baseUrl)
                .when()
                .get(endpoint)
                .then()
                .statusCode(200)
                .extract().response();

        System.out.println("Response: " + response.asString());

        String actualResult = response.asString().contains("id") ? "PASS" : "FAIL";
        excel.setCellData("Tests", rowIndex, 6, actualResult);

        Assert.assertEquals(actualResult, "PASS");
    }
}
